<?php

/**
 * This is the model base class for the table "empresa".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Empresa".
 *
 * Columns in table "empresa" available as properties of the model,
 * followed by relations of table "empresa" available as properties of the model.
 *
 * @property integer $idempresa
 * @property string $documento
 * @property string $nome
 * @property string $descricao
 * @property integer $dogrupo
 *
 * @property Conta[] $contas
 * @property User[] $users
 * @property Fluxo[] $fluxos
 * @property Fluxo[] $fluxos1
 */
abstract class BaseEmpresa extends SActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'empresa';
	}

	public static function representingColumn() {
		return 'documento';
	}

	public function rules() {
		return array(
			array('nome', 'required'),
			array('dogrupo', 'numerical', 'integerOnly'=>true),
			array('documento', 'length', 'max'=>20),
			array('nome, descricao', 'length', 'max'=>255),
			array('descricao, dogrupo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idempresa, documento, nome, descricao, dogrupo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'contas' => array(self::MANY_MANY, 'Conta', 'empresa_conta(idempresa, idconta)'),
			'users' => array(self::MANY_MANY, 'User', 'empresa_user(idempresa, iduser)'),
			'fluxos' => array(self::HAS_MANY, 'Fluxo', 'idempresa_origem'),
			'fluxos1' => array(self::HAS_MANY, 'Fluxo', 'idempresa_destino'),
		);
	}

	public function pivotModels() {
		return array(
			'contas' => 'EmpresaConta',
			'users' => 'EmpresaUser',
		);
	}

	public function attributeLabels() {
		return array(
			'idempresa' => Yii::t('app', 'Idempresa'),
			'documento' => Yii::t('app', 'CPF/CNPJ'),
			'nome' => Yii::t('app', 'Nome'),
			'descricao' => Yii::t('app', 'Descricao'),
			'dogrupo' => Yii::t('app', 'Pertence ao grupo '),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idempresa', $this->idempresa);
		$criteria->compare('documento', $this->documento, true);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('descricao', $this->descricao, true);
		$criteria->compare('dogrupo', $this->dogrupo);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}