<?php

/**
 * This is the model base class for the table "PED_CAB_PEDIDO".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PEDCABPEDIDO".
 *
 * Columns in table "PED_CAB_PEDIDO" available as properties of the model,
 * followed by relations of table "PED_CAB_PEDIDO" available as properties of the model.
 *
 * @property double $PED_ID_CAB_PED
 * @property double $SPED_ID_CPAG
 * @property double $ID_CLIENTE_CPED
 * @property double $PED_NUM_PED_CLIENTE_CPED
 * @property string $PED_DATA_PREV_ENTREGA_CPED
 * @property string $PED_DATA_PEDIDO_CPED
 * @property string $PED_STATUS_PEDIDO_CPED
 * @property double $PED_TOTAL_PEDIDO_CPED
 * @property double $PED_ID_USUARIO_CAD_CPED
 * @property double $PED_ID_USUARIO_CANC_CPED
 * @property string $PED_DATA_CANC_CPED
 * @property double $IDNOTAFISCAL
 * @property double $PED_TOT_PESO_LIQ_CPED
 * @property double $PED_TOT_PESO_BRUTO_CPED
 * @property double $PED_TOT_QUANT_EMB_CPED
 * @property string $PED_TIPO_PEDIDO_CPED
 * @property string $PED_EMITE_NOTA_FISCAL_CPED
 * @property string $PED_FAT_BARBACENA_CPED
 * @property string $PED_SEM_ROTEIRO_CPED
 * @property double $PED_ID_COORDENADOR_CPED
 * @property double $PED_ID_PROMOTOR_CPED
 *
 * @property PEDCONDPAGAMENTO $sPEDIDCPAG
 * @property SYSUSUARIO $pEDIDUSUARIOCADCPED
 * @property SYSUSUARIO $pEDIDUSUARIOCANCCPED
 * @property TBLNOTAFISCAL $iDNOTAFISCAL
 * @property PEDITEMPEDIDO[] $pEDITEMPEDIDOs
 */
abstract class BasePEDCABPEDIDO extends OActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'PED_CAB_PEDIDO';
	}

	public static function representingColumn() {
		return 'PED_DATA_PREV_ENTREGA_CPED';
	}

	public function rules() {
		return array(
			array('SPED_ID_CPAG, ID_CLIENTE_CPED, PED_NUM_PED_CLIENTE_CPED, PED_TOTAL_PEDIDO_CPED, PED_ID_USUARIO_CAD_CPED, PED_ID_USUARIO_CANC_CPED, IDNOTAFISCAL, PED_TOT_PESO_LIQ_CPED, PED_TOT_PESO_BRUTO_CPED, PED_TOT_QUANT_EMB_CPED, PED_ID_COORDENADOR_CPED, PED_ID_PROMOTOR_CPED', 'numerical'),
			array('PED_STATUS_PEDIDO_CPED, PED_TIPO_PEDIDO_CPED, PED_EMITE_NOTA_FISCAL_CPED, PED_FAT_BARBACENA_CPED, PED_SEM_ROTEIRO_CPED', 'length', 'max'=>1),
			array('PED_DATA_PREV_ENTREGA_CPED, PED_DATA_PEDIDO_CPED, PED_DATA_CANC_CPED', 'safe'),
			array('SPED_ID_CPAG, ID_CLIENTE_CPED, PED_NUM_PED_CLIENTE_CPED, PED_DATA_PREV_ENTREGA_CPED, PED_DATA_PEDIDO_CPED, PED_STATUS_PEDIDO_CPED, PED_TOTAL_PEDIDO_CPED, PED_ID_USUARIO_CAD_CPED, PED_ID_USUARIO_CANC_CPED, PED_DATA_CANC_CPED, IDNOTAFISCAL, PED_TOT_PESO_LIQ_CPED, PED_TOT_PESO_BRUTO_CPED, PED_TOT_QUANT_EMB_CPED, PED_TIPO_PEDIDO_CPED, PED_EMITE_NOTA_FISCAL_CPED, PED_FAT_BARBACENA_CPED, PED_SEM_ROTEIRO_CPED, PED_ID_COORDENADOR_CPED, PED_ID_PROMOTOR_CPED', 'default', 'setOnEmpty' => true, 'value' => null),
			array('PED_ID_CAB_PED, SPED_ID_CPAG, ID_CLIENTE_CPED, PED_NUM_PED_CLIENTE_CPED, PED_DATA_PREV_ENTREGA_CPED, PED_DATA_PEDIDO_CPED, PED_STATUS_PEDIDO_CPED, PED_TOTAL_PEDIDO_CPED, PED_ID_USUARIO_CAD_CPED, PED_ID_USUARIO_CANC_CPED, PED_DATA_CANC_CPED, IDNOTAFISCAL, PED_TOT_PESO_LIQ_CPED, PED_TOT_PESO_BRUTO_CPED, PED_TOT_QUANT_EMB_CPED, PED_TIPO_PEDIDO_CPED, PED_EMITE_NOTA_FISCAL_CPED, PED_FAT_BARBACENA_CPED, PED_SEM_ROTEIRO_CPED, PED_ID_COORDENADOR_CPED, PED_ID_PROMOTOR_CPED', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'sPEDIDCPAG' => array(self::BELONGS_TO, 'PEDCONDPAGAMENTO', 'SPED_ID_CPAG'),
			'pEDIDUSUARIOCADCPED' => array(self::BELONGS_TO, 'SYSUSUARIO', 'PED_ID_USUARIO_CAD_CPED'),
			'pEDIDUSUARIOCANCCPED' => array(self::BELONGS_TO, 'SYSUSUARIO', 'PED_ID_USUARIO_CANC_CPED'),
			'iDNOTAFISCAL' => array(self::BELONGS_TO, 'TBLNOTAFISCAL', 'IDNOTAFISCAL'),
			'pEDITEMPEDIDOs' => array(self::HAS_MANY, 'PEDITEMPEDIDO', 'PED_ID_CAB_PED'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'PED_ID_CAB_PED' => Yii::t('app', 'Ped Id Cab Ped'),
			'SPED_ID_CPAG' => Yii::t('app', 'Sped Id Cpag'),
			'ID_CLIENTE_CPED' => Yii::t('app', 'Id Cliente Cped'),
			'PED_NUM_PED_CLIENTE_CPED' => Yii::t('app', 'Ped Num Ped Cliente Cped'),
			'PED_DATA_PREV_ENTREGA_CPED' => Yii::t('app', 'Ped Data Prev Entrega Cped'),
			'PED_DATA_PEDIDO_CPED' => Yii::t('app', 'Ped Data Pedido Cped'),
			'PED_STATUS_PEDIDO_CPED' => Yii::t('app', 'Ped Status Pedido Cped'),
			'PED_TOTAL_PEDIDO_CPED' => Yii::t('app', 'Ped Total Pedido Cped'),
			'PED_ID_USUARIO_CAD_CPED' => Yii::t('app', 'Ped Id Usuario Cad Cped'),
			'PED_ID_USUARIO_CANC_CPED' => Yii::t('app', 'Ped Id Usuario Canc Cped'),
			'PED_DATA_CANC_CPED' => Yii::t('app', 'Ped Data Canc Cped'),
			'IDNOTAFISCAL' => Yii::t('app', 'Idnotafiscal'),
			'PED_TOT_PESO_LIQ_CPED' => Yii::t('app', 'Ped Tot Peso Liq Cped'),
			'PED_TOT_PESO_BRUTO_CPED' => Yii::t('app', 'Ped Tot Peso Bruto Cped'),
			'PED_TOT_QUANT_EMB_CPED' => Yii::t('app', 'Ped Tot Quant Emb Cped'),
			'PED_TIPO_PEDIDO_CPED' => Yii::t('app', 'Ped Tipo Pedido Cped'),
			'PED_EMITE_NOTA_FISCAL_CPED' => Yii::t('app', 'Ped Emite Nota Fiscal Cped'),
			'PED_FAT_BARBACENA_CPED' => Yii::t('app', 'Ped Fat Barbacena Cped'),
			'PED_SEM_ROTEIRO_CPED' => Yii::t('app', 'Ped Sem Roteiro Cped'),
			'PED_ID_COORDENADOR_CPED' => Yii::t('app', 'Ped Id Coordenador Cped'),
			'PED_ID_PROMOTOR_CPED' => Yii::t('app', 'Ped Id Promotor Cped'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('PED_ID_CAB_PED', $this->PED_ID_CAB_PED);
		$criteria->compare('SPED_ID_CPAG', $this->SPED_ID_CPAG);
		$criteria->compare('ID_CLIENTE_CPED', $this->ID_CLIENTE_CPED);
		$criteria->compare('PED_NUM_PED_CLIENTE_CPED', $this->PED_NUM_PED_CLIENTE_CPED);
		$criteria->compare('PED_DATA_PREV_ENTREGA_CPED', $this->PED_DATA_PREV_ENTREGA_CPED, true);
		$criteria->compare('PED_DATA_PEDIDO_CPED', $this->PED_DATA_PEDIDO_CPED, true);
		$criteria->compare('PED_STATUS_PEDIDO_CPED', $this->PED_STATUS_PEDIDO_CPED, true);
		$criteria->compare('PED_TOTAL_PEDIDO_CPED', $this->PED_TOTAL_PEDIDO_CPED);
		$criteria->compare('PED_ID_USUARIO_CAD_CPED', $this->PED_ID_USUARIO_CAD_CPED);
		$criteria->compare('PED_ID_USUARIO_CANC_CPED', $this->PED_ID_USUARIO_CANC_CPED);
		$criteria->compare('PED_DATA_CANC_CPED', $this->PED_DATA_CANC_CPED, true);
		$criteria->compare('IDNOTAFISCAL', $this->IDNOTAFISCAL);
		$criteria->compare('PED_TOT_PESO_LIQ_CPED', $this->PED_TOT_PESO_LIQ_CPED);
		$criteria->compare('PED_TOT_PESO_BRUTO_CPED', $this->PED_TOT_PESO_BRUTO_CPED);
		$criteria->compare('PED_TOT_QUANT_EMB_CPED', $this->PED_TOT_QUANT_EMB_CPED);
		$criteria->compare('PED_TIPO_PEDIDO_CPED', $this->PED_TIPO_PEDIDO_CPED, true);
		$criteria->compare('PED_EMITE_NOTA_FISCAL_CPED', $this->PED_EMITE_NOTA_FISCAL_CPED, true);
		$criteria->compare('PED_FAT_BARBACENA_CPED', $this->PED_FAT_BARBACENA_CPED, true);
		$criteria->compare('PED_SEM_ROTEIRO_CPED', $this->PED_SEM_ROTEIRO_CPED, true);
		$criteria->compare('PED_ID_COORDENADOR_CPED', $this->PED_ID_COORDENADOR_CPED);
		$criteria->compare('PED_ID_PROMOTOR_CPED', $this->PED_ID_PROMOTOR_CPED);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}