<?php

/**
 * This is the model base class for the table "formaspg".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Formaspg".
 *
 * Columns in table "formaspg" available as properties of the model,
 * followed by relations of table "formaspg" available as properties of the model.
 *
 * @property integer $idformaspg
 * @property string $nome
 * @property integer $detalha
 *
 * @property Fluxo[] $fluxos
 */
abstract class BaseFormaspg extends SActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'formaspg';
	}

	public static function representingColumn() {
		return 'nome';
	}

	public function rules() {
		return array(
			array('nome', 'required'),
			array('detalha', 'numerical', 'integerOnly'=>true),
			array('nome', 'length', 'max'=>100),
			array('detalha', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idformaspg, nome, detalha', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'fluxos' => array(self::HAS_MANY, 'Fluxo', 'idformaspg'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idformaspg' => Yii::t('app', 'Idformaspg'),
			'nome' => Yii::t('app', 'Nome'),
			'detalha' => Yii::t('app', 'Detalha'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idformaspg', $this->idformaspg);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('detalha', $this->detalha);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}