<?php

/**
 * This is the model base class for the table "ccusto".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Ccusto".
 *
 * Columns in table "ccusto" available as properties of the model,
 * followed by relations of table "ccusto" available as properties of the model.
 *
 * @property integer $idccusto
 * @property string $descricao
 *
 * @property Fluxo[] $fluxos
 */
abstract class BaseCcusto extends SActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ccusto';
	}

	public static function representingColumn() {
		return 'descricao';
	}

	public function rules() {
		return array(
			array('descricao', 'length', 'max'=>45),
			array('descricao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idccusto, descricao', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'fluxos' => array(self::HAS_MANY, 'Fluxo', 'idccusto'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idccusto' => Yii::t('app', 'Idccusto'),
			'descricao' => Yii::t('app', 'Descricao'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idccusto', $this->idccusto);
		$criteria->compare('descricao', $this->descricao, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}