<?php

/**
 * This is the model base class for the table "empresa_conta".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmpresaConta".
 *
 * Columns in table "empresa_conta" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idempresa
 * @property integer $idconta
 *
 */
abstract class BaseEmpresaConta extends SActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'empresa_conta';
	}

	public static function representingColumn() {
		return array(
			'idempresa',
			'idconta',
		);
	}

	public function rules() {
		return array(
			array('idempresa, idconta', 'required'),
			array('idempresa, idconta', 'numerical', 'integerOnly'=>true),
			array('idempresa, idconta', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idempresa' => Yii::t('app', 'Idempresa'),
			'idconta' => Yii::t('app', 'Idconta'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idempresa', $this->idempresa);
		$criteria->compare('idconta', $this->idconta);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}