<?php

/**
 * This is the model base class for the table "conta".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Conta".
 *
 * Columns in table "conta" available as properties of the model,
 * followed by relations of table "conta" available as properties of the model.
 *
 * @property integer $idconta
 * @property string $descricao
 *
 * @property Empresa[] $empresas
 * @property Fluxo[] $fluxos
 */
abstract class BaseConta extends SActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'conta';
	}

	public static function representingColumn() {
		return 'descricao';
	}

	public function rules() {
		return array(
			array('descricao', 'required'),
			array('descricao', 'length', 'max'=>45),
			array('idconta, descricao', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'empresas' => array(self::MANY_MANY, 'Empresa', 'empresa_conta(idconta, idempresa)'),
			'fluxos' => array(self::HAS_MANY, 'Fluxo', 'idconta'),
		);
	}

	public function pivotModels() {
		return array(
			'empresas' => 'EmpresaConta',
		);
	}

	public function attributeLabels() {
		return array(
			'idconta' => Yii::t('app', 'Idconta'),
			'descricao' => Yii::t('app', 'Descricao'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idconta', $this->idconta);
		$criteria->compare('descricao', $this->descricao, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}