<?php

/**
 * This is the model base class for the table "empresa_user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmpresaUser".
 *
 * Columns in table "empresa_user" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idempresa
 * @property integer $iduser
 *
 */
abstract class BaseEmpresaUser extends SActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'empresa_user';
	}

	public static function representingColumn() {
		return array(
			'idempresa',
			'iduser',
		);
	}

	public function rules() {
		return array(
			array('idempresa, iduser', 'required'),
			array('idempresa, iduser', 'numerical', 'integerOnly'=>true),
			array('idempresa, iduser', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idempresa' => Yii::t('app', 'Idempresa'),
			'iduser' => Yii::t('app', 'Iduser'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idempresa', $this->idempresa);
		$criteria->compare('iduser', $this->iduser);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}