<?php

/**
 * This is the model base class for the table "fluxo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Fluxo".
 *
 * Columns in table "fluxo" available as properties of the model,
 * followed by relations of table "fluxo" available as properties of the model.
 *
 * @property string $idfluxo
 * @property integer $idfluxo_forma
 * @property integer $idclifor
 * @property integer $idusuario
 * @property integer $ativo
 * @property integer $previsao
 * @property string $data_cadastro
 *
 * @property CadClifor $idclifor0
 * @property FluxoForma $idfluxoForma
 * @property User $idusuario0
 * @property FluxoFrete[] $fluxoFretes
 * @property FluxoNf[] $fluxoNfs
 * @property FluxoParcelas[] $fluxoParcelases
 * @property FluxoProdutos[] $fluxoProdutoses
 * @property FluxoStatus[] $fluxoStatuses
 */
abstract class BaseFluxo extends SActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'fluxo';
	}

	public static function representingColumn() {
		return 'data_cadastro';
	}

	public function rules() {
		return array(
			array('idfluxo_forma, idclifor, idusuario, data_cadastro', 'required'),
			array('idfluxo_forma, idclifor, idusuario, ativo, previsao', 'numerical', 'integerOnly'=>true),
			array('ativo, previsao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idfluxo, idfluxo_forma, idclifor, idusuario, ativo, previsao, data_cadastro', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idclifor0' => array(self::BELONGS_TO, 'CadClifor', 'idclifor'),
			'idfluxoForma' => array(self::BELONGS_TO, 'FluxoForma', 'idfluxo_forma'),
			'idusuario0' => array(self::BELONGS_TO, 'User', 'idusuario'),
			'fluxoFretes' => array(self::HAS_MANY, 'FluxoFrete', 'idfluxo'),
			'fluxoNfs' => array(self::HAS_MANY, 'FluxoNf', 'idfluxo'),
			'fluxoParcelases' => array(self::HAS_MANY, 'FluxoParcelas', 'idfluxo'),
			'fluxoProdutoses' => array(self::HAS_MANY, 'FluxoProdutos', 'idfluxo'),
			'fluxoStatuses' => array(self::HAS_MANY, 'FluxoStatus', 'idfluxo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idfluxo' => Yii::t('app', 'Idfluxo'),
			'idfluxo_forma' => Yii::t('app', 'Idfluxo Forma'),
			'idclifor' => Yii::t('app', 'Idclifor'),
			'idusuario' => Yii::t('app', 'Idusuario'),
			'ativo' => Yii::t('app', 'Ativo'),
			'previsao' => Yii::t('app', 'Previsao'),
			'data_cadastro' => Yii::t('app', 'Data Cadastro'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idfluxo', $this->idfluxo, true);
		$criteria->compare('idfluxo_forma', $this->idfluxo_forma);
		$criteria->compare('idclifor', $this->idclifor);
		$criteria->compare('idusuario', $this->idusuario);
		$criteria->compare('ativo', $this->ativo);
		$criteria->compare('previsao', $this->previsao);
		$criteria->compare('data_cadastro', $this->data_cadastro, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}