<?php

/**
 * This is the model base class for the table "cad_status".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CadStatus".
 *
 * Columns in table "cad_status" available as properties of the model,
 * followed by relations of table "cad_status" available as properties of the model.
 *
 * @property integer $idstatus
 * @property string $descricao
 * @property integer $ativo
 *
 * @property FluxoForma[] $fluxoFormas
 * @property FluxoStatus[] $fluxoStatuses
 */
abstract class BaseCadStatus extends SActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cad_status';
	}

	public static function representingColumn() {
		return 'descricao';
	}

	public function rules() {
		return array(
			array('ativo', 'numerical', 'integerOnly'=>true),
			array('descricao', 'length', 'max'=>100),
			array('descricao, ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idstatus, descricao, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'fluxoFormas' => array(self::MANY_MANY, 'FluxoForma', 'fforma_status(cad_status_idstatus, fluxo_forma_idfluxo_forma)'),
			'fluxoStatuses' => array(self::HAS_MANY, 'FluxoStatus', 'idstatus'),
		);
	}

	public function pivotModels() {
		return array(
			'fluxoFormas' => 'FformaStatus',
		);
	}

	public function attributeLabels() {
		return array(
			'idstatus' => Yii::t('app', 'Idstatus'),
			'descricao' => Yii::t('app', 'Descricao'),
			'ativo' => Yii::t('app', 'Ativo'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idstatus', $this->idstatus);
		$criteria->compare('descricao', $this->descricao, true);
		$criteria->compare('ativo', $this->ativo);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}