<?php

/**
 * This is the model base class for the table "fluxo_produtos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FluxoProdutos".
 *
 * Columns in table "fluxo_produtos" available as properties of the model,
 * followed by relations of table "fluxo_produtos" available as properties of the model.
 *
 * @property string $idfluxo_produtos
 * @property string $idfluxo
 * @property integer $idprodutos
 * @property integer $idcad_cfop
 * @property integer $idcad_cst
 * @property string $qtde_sol
 * @property string $qtde_rec
 * @property string $valor_previsao
 * @property string $valor_unitario
 * @property string $valor_tabela
 * @property string $fator_corr
 * @property string $desconto
 * @property string $acrescimo
 * @property string $icms_bc
 * @property string $icms_valor
 * @property string $icms_aliquota
 * @property string $ipi_valor
 * @property string $ipi_aliquota
 * @property integer $idcad_ncm
 *
 * @property CadProdutos $idprodutos0
 * @property CadCfop $idcadCfop
 * @property CadCst $idcadCst
 * @property CadNcm $idcadNcm
 * @property Fluxo $idfluxo0
 * @property FluxoProdutosValidade[] $fluxoProdutosValidades
 * @property FluxoWms[] $fluxoWms
 */
abstract class BaseFluxoProdutos extends SActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'fluxo_produtos';
	}

	public static function representingColumn() {
		return 'qtde_sol';
	}

	public function rules() {
		return array(
			array('idfluxo, idprodutos, idcad_cfop, idcad_cst, idcad_ncm', 'required'),
			array('idprodutos, idcad_cfop, idcad_cst, idcad_ncm', 'numerical', 'integerOnly'=>true),
			array('idfluxo', 'length', 'max'=>20),
			array('qtde_sol, qtde_rec', 'length', 'max'=>7),
			array('valor_previsao, valor_unitario, valor_tabela, desconto, acrescimo, icms_bc, icms_valor, ipi_valor', 'length', 'max'=>9),
			array('fator_corr', 'length', 'max'=>5),
			array('icms_aliquota, ipi_aliquota', 'length', 'max'=>3),
			array('qtde_sol, qtde_rec, valor_previsao, valor_unitario, valor_tabela, fator_corr, desconto, acrescimo, icms_bc, icms_valor, icms_aliquota, ipi_valor, ipi_aliquota', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idfluxo_produtos, idfluxo, idprodutos, idcad_cfop, idcad_cst, qtde_sol, qtde_rec, valor_previsao, valor_unitario, valor_tabela, fator_corr, desconto, acrescimo, icms_bc, icms_valor, icms_aliquota, ipi_valor, ipi_aliquota, idcad_ncm', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idprodutos0' => array(self::BELONGS_TO, 'CadProdutos', 'idprodutos'),
			'idcadCfop' => array(self::BELONGS_TO, 'CadCfop', 'idcad_cfop'),
			'idcadCst' => array(self::BELONGS_TO, 'CadCst', 'idcad_cst'),
			'idcadNcm' => array(self::BELONGS_TO, 'CadNcm', 'idcad_ncm'),
			'idfluxo0' => array(self::BELONGS_TO, 'Fluxo', 'idfluxo'),
			'fluxoProdutosValidades' => array(self::HAS_MANY, 'FluxoProdutosValidade', 'idfluxo_produtos'),
			'fluxoWms' => array(self::HAS_MANY, 'FluxoWms', 'idfluxo_produtos'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idfluxo_produtos' => Yii::t('app', 'Idfluxo Produtos'),
			'idfluxo' => Yii::t('app', 'Idfluxo'),
			'idprodutos' => Yii::t('app', 'Idprodutos'),
			'idcad_cfop' => Yii::t('app', 'Idcad Cfop'),
			'idcad_cst' => Yii::t('app', 'Idcad Cst'),
			'qtde_sol' => Yii::t('app', 'Qtde Sol'),
			'qtde_rec' => Yii::t('app', 'Qtde Rec'),
			'valor_previsao' => Yii::t('app', 'Valor Previsao'),
			'valor_unitario' => Yii::t('app', 'Valor Unitario'),
			'valor_tabela' => Yii::t('app', 'Valor Tabela'),
			'fator_corr' => Yii::t('app', 'Fator Corr'),
			'desconto' => Yii::t('app', 'Desconto'),
			'acrescimo' => Yii::t('app', 'Acrescimo'),
			'icms_bc' => Yii::t('app', 'Icms Bc'),
			'icms_valor' => Yii::t('app', 'Icms Valor'),
			'icms_aliquota' => Yii::t('app', 'Icms Aliquota'),
			'ipi_valor' => Yii::t('app', 'Ipi Valor'),
			'ipi_aliquota' => Yii::t('app', 'Ipi Aliquota'),
			'idcad_ncm' => Yii::t('app', 'Idcad Ncm'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idfluxo_produtos', $this->idfluxo_produtos, true);
		$criteria->compare('idfluxo', $this->idfluxo);
		$criteria->compare('idprodutos', $this->idprodutos);
		$criteria->compare('idcad_cfop', $this->idcad_cfop);
		$criteria->compare('idcad_cst', $this->idcad_cst);
		$criteria->compare('qtde_sol', $this->qtde_sol, true);
		$criteria->compare('qtde_rec', $this->qtde_rec, true);
		$criteria->compare('valor_previsao', $this->valor_previsao, true);
		$criteria->compare('valor_unitario', $this->valor_unitario, true);
		$criteria->compare('valor_tabela', $this->valor_tabela, true);
		$criteria->compare('fator_corr', $this->fator_corr, true);
		$criteria->compare('desconto', $this->desconto, true);
		$criteria->compare('acrescimo', $this->acrescimo, true);
		$criteria->compare('icms_bc', $this->icms_bc, true);
		$criteria->compare('icms_valor', $this->icms_valor, true);
		$criteria->compare('icms_aliquota', $this->icms_aliquota, true);
		$criteria->compare('ipi_valor', $this->ipi_valor, true);
		$criteria->compare('ipi_aliquota', $this->ipi_aliquota, true);
		$criteria->compare('idcad_ncm', $this->idcad_ncm);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}