<?php

/**
 * This is the model base class for the table "fforma_status".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FformaStatus".
 *
 * Columns in table "fforma_status" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $fluxo_forma_idfluxo_forma
 * @property integer $cad_status_idstatus
 *
 */
abstract class BaseFformaStatus extends SActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'fforma_status';
	}

	public static function representingColumn() {
		return array(
			'fluxo_forma_idfluxo_forma',
			'cad_status_idstatus',
		);
	}

	public function rules() {
		return array(
			array('fluxo_forma_idfluxo_forma, cad_status_idstatus', 'required'),
			array('fluxo_forma_idfluxo_forma, cad_status_idstatus', 'numerical', 'integerOnly'=>true),
			array('fluxo_forma_idfluxo_forma, cad_status_idstatus', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'fluxo_forma_idfluxo_forma' => Yii::t('app', 'Fluxo Forma Idfluxo Forma'),
			'cad_status_idstatus' => Yii::t('app', 'Cad Status Idstatus'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('fluxo_forma_idfluxo_forma', $this->fluxo_forma_idfluxo_forma);
		$criteria->compare('cad_status_idstatus', $this->cad_status_idstatus);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}