<?php

/**
 * This is the model base class for the table "cad_clifor".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CadClifor".
 *
 * Columns in table "cad_clifor" available as properties of the model,
 * followed by relations of table "cad_clifor" available as properties of the model.
 *
 * @property integer $idclifor
 * @property integer $idtipo
 * @property string $razao_social
 * @property string $nome_fantasia
 * @property string $doc
 * @property string $ie
 * @property string $data_cadastro
 * @property string $data_atualizacao
 * @property integer $ativo
 *
 * @property CadCliforTipo $idtipo0
 * @property CadCliforEndereco[] $cadCliforEnderecos
 * @property CadCliforTelefone[] $cadCliforTelefones
 * @property User[] $users
 * @property CadRelProdutosPrecoClifor[] $cadRelProdutosPrecoClifors
 * @property Fluxo[] $fluxos
 * @property FluxoFrete[] $fluxoFretes
 * @property FluxoNf[] $fluxoNfs
 */
abstract class BaseCadClifor extends SActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cad_clifor';
	}

	public static function representingColumn() {
		return 'razao_social';
	}

	public function rules() {
		return array(
			array('idtipo', 'required'),
			array('idtipo, ativo', 'numerical', 'integerOnly'=>true),
			array('razao_social, nome_fantasia', 'length', 'max'=>255),
			array('doc, ie', 'length', 'max'=>20),
			//array('ie','validaInscricao'),
			array('data_cadastro, data_atualizacao', 'safe'),
			array('razao_social, nome_fantasia, doc, ie, data_cadastro, data_atualizacao, ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idclifor, idtipo, razao_social, nome_fantasia, doc, ie, data_cadastro, data_atualizacao, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idtipo0' => array(self::BELONGS_TO, 'CadCliforTipo', 'idtipo'),
			//'cadCliforEnderecos' => array(self::HAS_MANY, 'CadCliforEndereco', 'idclifor'),
			//'cadCliforTelefones' => array(self::HAS_MANY, 'CadCliforTelefone', 'idclifor'),
			'users' => array(self::MANY_MANY, 'User', 'cad_clifor_user(idclifor, iduser)'),
			//'cadRelProdutosPrecoClifors' => array(self::HAS_MANY, 'CadRelProdutosPrecoClifor', 'idclifor'),
			//'fluxos' => array(self::HAS_MANY, 'Fluxo', 'idclifor'),
			//'fluxoFretes' => array(self::HAS_MANY, 'FluxoFrete', 'idclifor'),
			//'fluxoNfs' => array(self::HAS_MANY, 'FluxoNf', 'idclifor'),
		);
	}

	public function pivotModels() {
		return array(
			'users' => 'CadCliforUser',
		);
	}

	public function attributeLabels() {
		return array(
			'idclifor' => Yii::t('app', 'Idclifor'),
			'idtipo' => Yii::t('app', 'Tipo'),
			'razao_social' => Yii::t('app', 'Razao Social'),
			'nome_fantasia' => Yii::t('app', 'Nome Fantasia'),
			'doc' => Yii::t('app', 'Documento (CNPJ/CPF)'),
			'ie' => Yii::t('app', 'Ie'),
			'data_cadastro' => Yii::t('app', 'Data Cadastro'),
			'data_atualizacao' => Yii::t('app', 'Data Atualizacao'),
			'ativo' => Yii::t('app', 'Ativo'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idclifor', $this->idclifor);
		$criteria->compare('idtipo', $this->idtipo);
		$criteria->compare('razao_social', $this->razao_social, true);
		$criteria->compare('nome_fantasia', $this->nome_fantasia, true);
		$criteria->compare('doc', $this->doc, true);
		$criteria->compare('ie', $this->ie, true);
		$criteria->compare('data_cadastro', $this->data_cadastro, true);
		$criteria->compare('data_atualizacao', $this->data_atualizacao, true);
		$criteria->compare('ativo', $this->ativo);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}