<?php

/**
 * This is the model base class for the table "cad_clifor_telefone".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CadCliforTelefone".
 *
 * Columns in table "cad_clifor_telefone" available as properties of the model,
 * followed by relations of table "cad_clifor_telefone" available as properties of the model.
 *
 * @property integer $idtelefone
 * @property integer $idclifor
 * @property integer $ddd
 * @property integer $telefone
 * @property string $contato
 *
 * @property CadClifor $idclifor0
 */
abstract class BaseCadCliforTelefone extends SActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cad_clifor_telefone';
	}

	public static function representingColumn() {
		return 'contato';
	}

	public function rules() {
		return array(
			array('idclifor', 'required'),
			array('idclifor, ddd, telefone', 'numerical', 'integerOnly'=>true),
			array('contato', 'length', 'max'=>100),
			array('ddd, telefone, contato', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idtelefone, idclifor, ddd, telefone, contato', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idclifor0' => array(self::BELONGS_TO, 'CadClifor', 'idclifor'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idtelefone' => Yii::t('app', 'Idtelefone'),
			'idclifor' => Yii::t('app', 'Idclifor'),
			'ddd' => Yii::t('app', 'Ddd'),
			'telefone' => Yii::t('app', 'Telefone'),
			'contato' => Yii::t('app', 'Contato'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idtelefone', $this->idtelefone);
		$criteria->compare('idclifor', $this->idclifor);
		$criteria->compare('ddd', $this->ddd);
		$criteria->compare('telefone', $this->telefone);
		$criteria->compare('contato', $this->contato, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}