<?php

/**
 * This is the model base class for the table "cad_clifor_user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CadCliforUser".
 *
 * Columns in table "cad_clifor_user" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $iduser
 * @property integer $idclifor
 *
 */
abstract class BaseCadCliforUser extends SActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cad_clifor_user';
	}

	public static function representingColumn() {
		return array(
			'iduser',
			'idclifor',
		);
	}

	public function rules() {
		return array(
			array('iduser, idclifor', 'required'),
			array('iduser, idclifor', 'numerical', 'integerOnly'=>true),
			array('iduser, idclifor', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'iduser' => Yii::t('app', 'Iduser'),
			'idclifor' => Yii::t('app', 'Idclifor'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('iduser', $this->iduser);
		$criteria->compare('idclifor', $this->idclifor);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}