<?php

/**
 * This is the model base class for the table "cad_clifor_tipo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CadCliforTipo".
 *
 * Columns in table "cad_clifor_tipo" available as properties of the model,
 * followed by relations of table "cad_clifor_tipo" available as properties of the model.
 *
 * @property integer $idtipo
 * @property string $descricao
 *
 * @property CadClifor[] $cadClifors
 */
abstract class BaseCadCliforTipo extends SActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cad_clifor_tipo';
	}

	public static function representingColumn() {
		return 'descricao';
	}

	public function rules() {
		return array(
			array('descricao', 'length', 'max'=>45),
			array('descricao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idtipo, descricao', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cadClifors' => array(self::HAS_MANY, 'CadClifor', 'idtipo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idtipo' => Yii::t('app', 'Idtipo'),
			'descricao' => Yii::t('app', 'Descricao'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idtipo', $this->idtipo);
		$criteria->compare('descricao', $this->descricao, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}