<?php

/**
 * This is the model base class for the table "cad_clifor_endereco".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CadCliforEndereco".
 *
 * Columns in table "cad_clifor_endereco" available as properties of the model,
 * followed by relations of table "cad_clifor_endereco" available as properties of the model.
 *
 * @property integer $idendereco
 * @property integer $idclifor
 * @property integer $idpais
 * @property integer $idcidade
 * @property integer $idestado
 * @property string $endereco
 * @property string $numero
 * @property string $complemento
 * @property string $bairro
 * @property string $cep
 * @property string $descricao
 *
 * @property CadClifor $idclifor0
 * @property CadPais $idpais0
 * @property CadCidade $idcidade0
 * @property CadEstado $idestado0
 */
abstract class BaseCadCliforEndereco extends SActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cad_clifor_endereco';
	}

	public static function representingColumn() {
		return 'endereco';
	}

	public function rules() {
		return array(
			array('idclifor, idpais, idcidade, idestado', 'required'),
			array('idclifor, idpais, idcidade, idestado', 'numerical', 'integerOnly'=>true),
			array('endereco, bairro', 'length', 'max'=>255),
			array('numero, complemento', 'length', 'max'=>45),
			array('cep', 'length', 'max'=>9),
			array('descricao', 'length', 'max'=>100),
			array('endereco, numero, complemento, bairro, cep, descricao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idendereco, idclifor, idpais, idcidade, idestado, endereco, numero, complemento, bairro, cep, descricao', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idclifor0' => array(self::BELONGS_TO, 'CadClifor', 'idclifor'),
			'idpais0' => array(self::BELONGS_TO, 'CadPais', 'idpais'),
			'idcidade0' => array(self::BELONGS_TO, 'CadCidade', 'idcidade'),
			'idestado0' => array(self::BELONGS_TO, 'CadEstado', 'idestado'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idendereco' => Yii::t('app', 'Idendereco'),
			'idclifor' => Yii::t('app', 'Idclifor'),
			'idpais' => Yii::t('app', 'Idpais'),
			'idcidade' => Yii::t('app', 'Idcidade'),
			'idestado' => Yii::t('app', 'Idestado'),
			'endereco' => Yii::t('app', 'Endereco'),
			'numero' => Yii::t('app', 'Numero'),
			'complemento' => Yii::t('app', 'Complemento'),
			'bairro' => Yii::t('app', 'Bairro'),
			'cep' => Yii::t('app', 'Cep'),
			'descricao' => Yii::t('app', 'Descricao'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idendereco', $this->idendereco);
		$criteria->compare('idclifor', $this->idclifor);
		$criteria->compare('idpais', $this->idpais);
		$criteria->compare('idcidade', $this->idcidade);
		$criteria->compare('idestado', $this->idestado);
		$criteria->compare('endereco', $this->endereco, true);
		$criteria->compare('numero', $this->numero, true);
		$criteria->compare('complemento', $this->complemento, true);
		$criteria->compare('bairro', $this->bairro, true);
		$criteria->compare('cep', $this->cep, true);
		$criteria->compare('descricao', $this->descricao, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}