<?php

/**
 * This is the model base class for the table "cad_produtos_unidade".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CadProdutosUnidade".
 *
 * Columns in table "cad_produtos_unidade" available as properties of the model,
 * followed by relations of table "cad_produtos_unidade" available as properties of the model.
 *
 * @property integer $idunidade
 * @property string $simbolo
 * @property string $unidade
 * @property integer $ativo
 *
 * @property CadNcm[] $cadNcms
 * @property CadProdutos[] $cadProdutoses
 * @property CadProdutosGrupos[] $cadProdutosGruposes
 * @property CadProdutosValidade[] $cadProdutosValidades
 */
abstract class BaseCadProdutosUnidade extends SActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cad_produtos_unidade';
	}

	public static function representingColumn() {
		return 'simbolo';
	}

	public function rules() {
		return array(
			array('ativo', 'numerical', 'integerOnly'=>true),
			array('simbolo', 'length', 'max'=>5),
			array('unidade', 'length', 'max'=>45),
			//array('ativo', 'length', 'max'=>1),
			array('simbolo, unidade, ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idunidade, simbolo, unidade, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			//'ncms' => array(self::HAS_MANY, 'CadNcm', 'idunidade'),
			'produtos' => array(self::HAS_MANY, 'CadProdutos', 'idunidade'),
			//'grupos_produtos' => array(self::HAS_MANY, 'CadProdutosGrupos', 'idunidade'),
			'validades' => array(self::HAS_MANY, 'CadProdutosValidade', 'idunidade'),
		);
	}

	public function pivotModels() {
		return array(
		); 
	}

	public function attributeLabels() {
		return array(
			'idunidade' => Yii::t('app', 'Idunidade'),
			'simbolo' => Yii::t('app', 'Simbolo'),
			'unidade' => Yii::t('app', 'Unidade'),
			'ativo' => Yii::t('app', 'Ativo'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idunidade', $this->idunidade);
		$criteria->compare('simbolo', $this->simbolo, true);
		$criteria->compare('unidade', $this->unidade, true);
		$criteria->compare('ativo', $this->ativo);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}