<?php

/**
 * This is the model base class for the table "cad_produtos_categoria".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CadProdutosCategoria".
 *
 * Columns in table "cad_produtos_categoria" available as properties of the model,
 * followed by relations of table "cad_produtos_categoria" available as properties of the model.
 *
 * @property integer $idprodutos_categoria
 * @property integer $idcategoria_pai
 * @property string $descricao
 * @property string $fator_corr
 * @property integer $ativo
 *
 * @property CadProdutos[] $cadProdutoses
 * @property CadProdutosCategoria $idcategoriaPai
 * @property CadProdutosCategoria[] $cadProdutosCategorias
 */
abstract class BaseCadProdutosCategoria extends SActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cad_produtos_categoria';
	}

	public static function representingColumn() {
		return 'descricao';
	}

	public function rules() {
		return array(
			array('idcategoria_pai, ativo', 'numerical', 'integerOnly'=>true),
			array('descricao', 'length', 'max'=>100),
			array('fator_corr', 'length', 'max'=>5),
			array('idcategoria_pai, descricao, fator_corr, ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idprodutos_categoria, idcategoria_pai, descricao, fator_corr, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'produtos' => array(self::HAS_MANY, 'CadProdutos', 'idcategoria'),
			'categoria_pai' => array(self::BELONGS_TO, 'CadProdutosCategoria', 'idcategoria_pai'),
			'categorias_filhas' => array(self::HAS_MANY, 'CadProdutosCategoria', 'idcategoria_pai'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idprodutos_categoria' => Yii::t('app', 'Idprodutos Categoria'),
			'idcategoria_pai' => Yii::t('app', 'Idcategoria Pai'),
			'descricao' => Yii::t('app', 'Descricao'),
			'fator_corr' => Yii::t('app', 'Fator Corr'),
			'ativo' => Yii::t('app', 'Ativo'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idprodutos_categoria', $this->idprodutos_categoria);
		$criteria->compare('idcategoria_pai', $this->idcategoria_pai);
		$criteria->compare('descricao', $this->descricao, true);
		$criteria->compare('fator_corr', $this->fator_corr, true);
		$criteria->compare('ativo', $this->ativo);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}