<?php

/**
 * This is the model base class for the table "cad_produtos_descricao".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CadProdutosDescricao".
 *
 * Columns in table "cad_produtos_descricao" available as properties of the model,
 * followed by relations of table "cad_produtos_descricao" available as properties of the model.
 *
 * @property integer $idprodutos_descricao
 * @property integer $idprodutos
 * @property string $tipo
 * @property string $descricao
 *
 * @property CadProdutos $idprodutos0
 */
abstract class BaseCadProdutosDescricao extends SActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cad_produtos_descricao';
	}

	public static function representingColumn() {
		return 'tipo';
	}

	public function rules() {
		return array(
			array('idprodutos', 'required'),
			array('idprodutos', 'numerical', 'integerOnly'=>true),
			array('tipo', 'length', 'max'=>100),
			array('descricao', 'safe'),
			array('tipo, descricao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idprodutos_descricao, idprodutos, tipo, descricao', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idprodutos0' => array(self::BELONGS_TO, 'CadProdutos', 'idprodutos'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idprodutos_descricao' => Yii::t('app', 'Idprodutos Descricao'),
			'idprodutos' => Yii::t('app', 'Idprodutos'),
			'tipo' => Yii::t('app', 'Tipo'),
			'descricao' => Yii::t('app', 'Descricao'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idprodutos_descricao', $this->idprodutos_descricao);
		$criteria->compare('idprodutos', $this->idprodutos);
		$criteria->compare('tipo', $this->tipo, true);
		$criteria->compare('descricao', $this->descricao, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}