<?php

/**
 * This is the model base class for the table "cad_produtos_precos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CadProdutosPrecos".
 *
 * Columns in table "cad_produtos_precos" available as properties of the model,
 * followed by relations of table "cad_produtos_precos" available as properties of the model.
 *
 * @property integer $idprodutos_precos
 * @property integer $idprodutos
 * @property string $valor_tabela
 * @property string $data_cadastro
 *
 * @property CadProdutos $idprodutos0
 */
abstract class BaseCadProdutosPrecos extends SActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cad_produtos_precos';
	}

	public static function representingColumn() {
		return 'valor_tabela';
	}

	public function rules() {
		return array(
			array('idprodutos', 'required'),
			array('idprodutos', 'numerical', 'integerOnly'=>true),
			array('valor_tabela', 'length', 'max'=>13),
			array('data_cadastro, iduser', 'safe'),
			array('valor_tabela, data_cadastro', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idprodutos_precos, idprodutos, valor_tabela, data_cadastro', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'produtos' => array(self::BELONGS_TO, 'CadProdutos', 'idprodutos'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idprodutos_precos' => Yii::t('app', 'Idprodutos Precos'),
			'idprodutos' => Yii::t('app', 'Idprodutos'),
			'valor_tabela' => Yii::t('app', 'Valor Tabela'),
			'data_cadastro' => Yii::t('app', 'Data Cadastro'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idprodutos_precos', $this->idprodutos_precos);
		$criteria->compare('idprodutos', $this->idprodutos);
		$criteria->compare('valor_tabela', $this->valor_tabela, true);
		$criteria->compare('data_cadastro', $this->data_cadastro, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}