<?php

/**
 * This is the model base class for the table "menu".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Menu".
 *
 * Columns in table "menu" available as properties of the model,
 * followed by relations of table "menu" available as properties of the model.
 *
 * @property integer $idmenu
 * @property string $label
 * @property string $url
 * @property integer $idmenu_pai
 * @property string $visible
 * @property integer $posicao
 * @property string $imagem
 * @property string $url_tipo
 *
 * @property Menu $idmenuPai
 * @property Menu[] $menus
 */
abstract class BaseMenu extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'menu';
	}

	public static function representingColumn() {
		return 'label';
	}

	public function rules() {
		return array(
			array('label, url', 'required'),
			array('idmenu_pai, posicao', 'numerical', 'integerOnly'=>true),
			array('label', 'length', 'max'=>100),
			array('url, imagem', 'length', 'max'=>255),
			array('url_tipo', 'length', 'max'=>10),
			array('visible', 'safe'),
			array('idmenu_pai, visible, posicao, imagem, url_tipo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idmenu, label, url, idmenu_pai, visible, posicao, imagem, url_tipo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idmenuPai' => array(self::BELONGS_TO, 'Menu', 'idmenu_pai'),
			'menus' => array(self::HAS_MANY, 'Menu', 'idmenu_pai'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idmenu' => Yii::t('app', 'Idmenu'),
			'label' => Yii::t('app', 'Label'),
			'url' => Yii::t('app', 'Url'),
			'idmenu_pai' => Yii::t('app', 'Pai'),
			'visible' => Yii::t('app', 'Visível'),
			'posicao' => Yii::t('app', 'Posição'),
			'imagem' => Yii::t('app', 'Imagem'),
			'url_tipo' => Yii::t('app', 'Tipo de URL'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idmenu', $this->idmenu);
		$criteria->compare('label', $this->label, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('idmenu_pai', $this->idmenu_pai);
		$criteria->compare('visible', $this->visible, true);
		$criteria->compare('posicao', $this->posicao);
		$criteria->compare('imagem', $this->imagem, true);
		$criteria->compare('url_tipo', $this->url_tipo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}