<?php

/**
 * This is the model base class for the table "tipo_nao_conformidade".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TipoNaoConformidade".
 *
 * Columns in table "tipo_nao_conformidade" available as properties of the model,
 * followed by relations of table "tipo_nao_conformidade" available as properties of the model.
 *
 * @property integer $idnconf
 * @property string $descricao
 *
 * @property Nconf[] $nconfs
 * @property Setor[] $setors
 */
abstract class BaseTipoNaoConformidade extends SActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tipo_nao_conformidade';
	}

	public static function representingColumn() {
		return 'descricao';
	}

	public function rules() {
		return array(
			array('descricao', 'length', 'max'=>255),
			array('descricao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idnconf, descricao', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'nconfs' => array(self::HAS_MANY, 'Nconf', 'idnconf_tipo'),
			'setors' => array(self::MANY_MANY, 'Setor', 'rel_setor_tnc(idnconf, idsetor)'),
		);
	}

	public function pivotModels() {
		return array(
			'setors' => 'RelSetorTnc',
		);
	}

	public function attributeLabels() {
		return array(
			'idnconf' => Yii::t('app', 'Idnconf'),
			'descricao' => Yii::t('app', 'Descricao'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idnconf', $this->idnconf);
		$criteria->compare('descricao', $this->descricao, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}