<?php

/**
 * This is the model base class for the table "setor".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Setor".
 *
 * Columns in table "setor" available as properties of the model,
 * followed by relations of table "setor" available as properties of the model.
 *
 * @property integer $idsetor
 * @property integer $iduser_responsavel
 * @property string $descricao
 *
 * @property Nconf[] $nconfs
 * @property User[] $users
 * @property TipoNaoConformidade[] $tipoNaoConformidades
 * @property User $iduserResponsavel
 */
abstract class BaseSetor extends SActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'setor';
	}

	public static function representingColumn() {
		return 'descricao';
	}

	public function rules() {
		return array(
			array('iduser_responsavel', 'required'),
			array('iduser_responsavel', 'numerical', 'integerOnly'=>true),
			array('descricao', 'length', 'max'=>255),
			array('descricao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idsetor, iduser_responsavel, descricao', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'nconfs' => array(self::HAS_MANY, 'Nconf', 'idsetor'),
			'users' => array(self::MANY_MANY, 'User', 'rel_User_setor(idsetor, iduser)'),
			'tipoNaoConformidades' => array(self::MANY_MANY, 'TipoNaoConformidade', 'rel_setor_tnc(idsetor, idnconf)'),
			'iduserResponsavel' => array(self::BELONGS_TO, 'User', 'iduser_responsavel'),
		);
	}

	public function pivotModels() {
		return array(
			'users' => 'RelUserSetor',
			'tipoNaoConformidades' => 'RelSetorTnc',
		);
	}

	public function attributeLabels() {
		return array(
			'idsetor' => Yii::t('app', 'Idsetor'),
			'iduser_responsavel' => Yii::t('app', 'User Responsável'),
			'descricao' => Yii::t('app', 'Descrição'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idsetor', $this->idsetor);
		$criteria->compare('iduser_responsavel', $this->iduser_responsavel);
		$criteria->compare('descricao', $this->descricao, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}