<?php

/**
 * This is the model base class for the table "nconf_user_leu".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NconfUserLeu".
 *
 * Columns in table "nconf_user_leu" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idnconf
 * @property integer $iduser
 * @property string $data_lido
 *
 */
abstract class BaseNconfUserLeu extends SActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'nconf_user_leu';
	}

	public static function representingColumn() {
		return array(
			'idnconf',
			'iduser',
		);
	}

	public function rules() {
		return array(
			array('idnconf, iduser, data_lido', 'required'),
			array('idnconf, iduser', 'numerical', 'integerOnly'=>true),
			array('idnconf, iduser, data_lido', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idnconf' => Yii::t('app', 'Idnconf'),
			'iduser' => Yii::t('app', 'Iduser'),
			'data_lido' => Yii::t('app', 'Data Lido'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idnconf', $this->idnconf);
		$criteria->compare('iduser', $this->iduser);
		$criteria->compare('data_lido', $this->data_lido, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}