<?php

/**
 * This is the model base class for the table "status".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Status".
 *
 * Columns in table "status" available as properties of the model,
 * followed by relations of table "status" available as properties of the model.
 *
 * @property integer $idstatus
 * @property string $descricao
 * @property integer $envia_email
 * @property integer $envia_historico
 *
 * @property RelStatusNconf[] $relStatusNconfs
 */
abstract class BaseStatus extends SActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'status';
	}

	public static function representingColumn() {
		return 'descricao';
	}

	public function rules() {
		return array(
			array('envia_email, envia_historico', 'numerical', 'integerOnly'=>true),
			array('descricao', 'length', 'max'=>255),
			array('descricao, envia_email, envia_historico', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idstatus, descricao, envia_email, envia_historico', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'relStatusNconfs' => array(self::HAS_MANY, 'RelStatusNconf', 'idstatus'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idstatus' => Yii::t('app', 'Idstatus'),
			'descricao' => Yii::t('app', 'Descricao'),
			'envia_email' => Yii::t('app', 'Envia Email'),
			'envia_historico' => Yii::t('app', 'Envia Historico'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idstatus', $this->idstatus);
		$criteria->compare('descricao', $this->descricao, true);
		$criteria->compare('envia_email', $this->envia_email);
		$criteria->compare('envia_historico', $this->envia_historico);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}